events {}

http {
    upstream backend_servers {
        server backend_0:80;
        server backend_1:80;
        server backend_2:80;
        server backend_3:80;
        server backend_4:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_http_version 1.0;
            proxy_set_header Connection close;
        }
    }
}